<a href="https://colab.research.google.com/github/Jhernandezh2/MetodosI_JulianaHernandez_MariaCamilaRamirez/blob/main/Parcial%203/Parcial_3_Markov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [156]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sympy as sp
from itertools import permutations
from itertools import combinations
from itertools import combinations_with_replacement
from itertools import product

***MARKOV***

Problema 2.

En  una  cadena  de  producci ́on  existen  dos  estaciones:   la  estaci ́on  de  producci ́on  y  laestaci ́on de empaque.  En la estaci ́on de producci ́on,  hay una probabilidad del 90% deque el producto avance a la estaci ́on de empaque y una probabilidad del 10% de que elproducto tenga un defecto, lo que hace que permanezca en la etapa de producci ́on.  Unavez que el producto llega a la estaci ́on de empaque, tiene una probabilidad del 95% de serenviado al mercado y una probabilidad del 5% de quedarse en la estaci ́on de empaque.

 (a)Describa las variables observables del problema.

 (b)  Defina el conjunto de estadosS={S1,S2,S3}.

 (c)  Construya la matriz de transici ́on de este proceso estoc ́astico.

 (d)  Encuentre el estado estable tanto algebraicamente como numéricamente.

 Recuerde πP=π para el estado estable.  ¿Qué interpretaci ́on le da al estado estable?
 (e)  Determine la probabilidad en estado estable de que ambas estaciones estén ocupadas al mismo tiempo.

 (f)  Determine  la  probabilidad  en  estado  estable  de  que  al  menos  una  estación  esté ocupada.

 (g)  Determine la probabilidad en estado estable de que la estación de producción esté vacía.


In [157]:
print("Variables: Estado del producto y transición entre estos")
print( "Los estados del producto son: Producción, Empaque y Mercado")
#Estados
States = np.array([0,1,2])
S = {1:"S1 Producción", 2:"S2 empaque", 3:"S3 Mercado"}

Variables: Estado del producto y transición entre estos
Los estados del producto son: Producción, Empaque y Mercado


In [158]:
#T Matrix
T = np.array([[0.10, 0.90, 0.00],[0.00, 0.05, 0.95],[0.00, 0.00, 1.00]])
np.sum(T,axis=1)

array([1., 1., 1.])

In [159]:
#Estado estable
#πP = π
#númerico
Initial = np.array([0.02,0.08,0.9])
States = np.array([Initial])

for i in range(10):
    Initial = np.dot(Initial,T)
    States = np.vstack((States,Initial))

States

array([[2.00000000e-02, 8.00000000e-02, 9.00000000e-01],
       [2.00000000e-03, 2.20000000e-02, 9.76000000e-01],
       [2.00000000e-04, 2.90000000e-03, 9.96900000e-01],
       [2.00000000e-05, 3.25000000e-04, 9.99655000e-01],
       [2.00000000e-06, 3.42500000e-05, 9.99963750e-01],
       [2.00000000e-07, 3.51250000e-06, 9.99996287e-01],
       [2.00000000e-08, 3.55625000e-07, 9.99999624e-01],
       [2.00000000e-09, 3.57812500e-08, 9.99999962e-01],
       [2.00000000e-10, 3.58906250e-09, 9.99999996e-01],
       [2.00000000e-11, 3.59453125e-10, 1.00000000e+00],
       [2.00000000e-12, 3.59726563e-11, 1.00000000e+00]])

In [160]:
EE = np.dot(States,T)
EE

array([[2.00000000e-03, 2.20000000e-02, 9.76000000e-01],
       [2.00000000e-04, 2.90000000e-03, 9.96900000e-01],
       [2.00000000e-05, 3.25000000e-04, 9.99655000e-01],
       [2.00000000e-06, 3.42500000e-05, 9.99963750e-01],
       [2.00000000e-07, 3.51250000e-06, 9.99996287e-01],
       [2.00000000e-08, 3.55625000e-07, 9.99999624e-01],
       [2.00000000e-09, 3.57812500e-08, 9.99999962e-01],
       [2.00000000e-10, 3.58906250e-09, 9.99999996e-01],
       [2.00000000e-11, 3.59453125e-10, 1.00000000e+00],
       [2.00000000e-12, 3.59726563e-11, 1.00000000e+00],
       [2.00000000e-13, 3.59863281e-12, 1.00000000e+00]])

In [161]:
pii= np.dot(np.dot(T,T),T)
pi=np.linalg.matrix_power(T,10)
pii

array([[1.00000e-03, 1.57500e-02, 9.83250e-01],
       [0.00000e+00, 1.25000e-04, 9.99875e-01],
       [0.00000e+00, 0.00000e+00, 1.00000e+00]])

In [162]:
print("Verificación: πP =")
print(np.dot(pi, T))
print("Suma de los elementos de pi:", np.sum(pi, axis = 1))

Verificación: πP =
[[1.00000000e-11 1.79912109e-10 1.00000000e+00]
 [0.00000000e+00 4.88281250e-15 1.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Suma de los elementos de pi: [1. 1. 1.]


In [163]:
#Matemática
pi1, pi2, pi3 = sp.symbols('pi1 pi2 pi3')
T = sp.Matrix(T)
equations = [
    pi1 - (0.10*pi1 + 0.00*pi2 + 0.00*pi3),
    pi2 - (0.90*pi1 + 0.05*pi2 + 0.00*pi3),
    pi3 - (0.00*pi1 + 0.95*pi2 + 1.00*pi3),
    pi1 + pi2 + pi3 - 1]

sol = sp.solve(equations, [pi1, pi2, pi3])
sol

{pi1: 0.0, pi2: 0.0, pi3: 1.00000000000000}

In [164]:
print("El estado estable es: ", S[3], ", ya que con una probabilidad de 100% los productos terminarán en este estado, de modo que no habrá producto en producción ni en empaque")

El estado estable es:  S3 Mercado , ya que con una probabilidad de 100% los productos terminarán en este estado, de modo que no habrá producto en producción ni en empaque


In [165]:
# Probabilidad de que ambas estaciones estén ocupadas
print("La probabilidad de que ambas estaciones estén ocupadas es: ", 0)

La probabilidad de que ambas estaciones estén ocupadas es:  0


Problema 3.

Resuelva  el  problema  anterior  suponiendo  que  el  2%  de  la  veces  el  cliente  regresa  elproducto y va directamente a producción.

P(S1∩S2)  =  0.043%,P(S1∪S2)  =  4.15%  y P(⌝S1)  =  97.87%.  

 El  estado  estable  esπ= [0.0213,0.0202,0.9585



In [166]:
pi2 = np.array([0.0213,0.0202,0.9585])

In [167]:
T2 = [[0.1, 0.9, 0],
     [0.0, 0.05, 0.95],
     [0.2, 0, 0.98]]

In [168]:
pii= np.dot(np.dot(T,T),T)

In [169]:
#P(ambas)
p = pi2[0]*pi2[1]*100
print("La probabilidad de que ambas estaciones estén ocupadas es: ", p, "%")

La probabilidad de que ambas estaciones estén ocupadas es:  0.043025999999999995 %


In [170]:
# Al menos una ocupada
P = (1-pi2[2])*100
print("La probabilidad de que al menos una estación esté ocupada es: ", P,"%")

La probabilidad de que al menos una estación esté ocupada es:  4.149999999999999 %


In [171]:
#Probabilidad de que producción esté vacía
P = (1-pi2[0])*100
print("La probabilidad de que la producción esté vacía es: ", P,"%")

La probabilidad de que la producción esté vacía es:  97.87 %


***HIDDEN MARKOV***

In [172]:
States = np.array([0,1])
S = {0:"J", 1:"B"}
Obs = np.array([2,1,1,1,2,1,2,1])
O = {1:"C", 2:"S"}

In [173]:
T = np.array([[0.8,0.2],[0.2,0.8]])
E = np.array([[0.5,0.5],[0.9,0.1]])

In [174]:
Prior = np.array([0.2,0.8])

In [175]:
def GetStates(States,N):
    CStates = list(combinations_with_replacement(States,N))
    Permu = []

    for i in CStates:
      p = list(permutations(i,N))
      for k in p:
        if k not in Permu:
          Permu.append(i)

    CStates = np.array(Permu)

    return CStates

In [176]:
def GetProb(T,E,Obs,States,Prior):
  n = len(Obs)
  p = Prior[States[0]]
  for i in range(n-1):
    p *= T[ States[i+1], States[i] ]

  for i in range(n):
   p *= E[States[i], Obs[i]-1 ]

  return p

In [ ]:
n = len(Obs)
HS = GetStates(States,n)
P = np.zeros(HS.shape[0])

for i in range(P.shape[0]):
  P[i] = GetProb(T,E,Obs,HS[i],Prior)
print(P)

In [ ]:
po = np.sum(P)
print(po)
P = P/po
ii = np.where(P == np.max(P))
print("Secuencia del más probables es: ", HS[ii], "con probabilidad de ",P[ii])

In [ ]:
OS = GetStates(Obs,8)
Nobs = OS.shape[0]
PObs = np.zeros(Nobs)

In [ ]:
for j in range(Nobs):
  dim = HS.shape[0]
  P = np.zeros(dim)
  for i in range(dim):
    P[i] = GetProb(T,E,OS[j],HS[i],Prior)

  PObs[j] = np.sum(P)

PObs

In [ ]:
PObs /= np.sum(PObs)

In [ ]:
plt.plot(PObs)
plt.plot(PObs)
plt.xlabel("Secuencias observadas")
plt.ylabel("Probabilidad")
plt.show()

In [ ]:
ii = np.where( PObs == np.max(PObs) )
print(OS[ii],PObs[ii])
np.sum(PObs)

In [ ]:
#Pandas
df = pd.DataFrame({"Secuencia": [tuple(seq) for seq in HS],"Probabilidad": P})

In [ ]:
df = df.sort_values(by="Probabilidad", ascending=False).reset_index(drop=True)
df["Probabilidad Acumulada"] = df["Probabilidad"].cumsum()

In [ ]:
threshold = 0.2
subset = df[df["Probabilidad Acumulada"] <= threshold]

In [ ]:
print("Secuencias más probables hasta alcanzar el 20% de probabilidad acumulada:")
print(subset)